ftsrg/theta

hu.bme.mit.theta.analysis/build.gradle, hu.bme.mit.theta.formalism.cfa/build.gradle, hu.bme.mit.theta.formalism.sts/build.gradle
The analysis project depends on Z3 only due to the tests, so I modified the dependency to be `testCompile`.
=> Modify Z3 dependency of analysis project to tests only

build.gradle.kts, subprojects/cfa-cli/README.md, subprojects/cfa-cli/src/main/java/hu/bme/mit/theta/cfa/cli/CfaCli.java, subprojects/cfa/src/main/java/hu/bme/mit/theta/cfa/dsl/CfaExpression.java, subprojects/sts-cli/README.md, subprojects/sts-cli/src/main/java/hu/bme/mit/theta/sts/cli/StsCli.java, subprojects/sts/src/main/java/hu/bme/mit/theta/sts/dsl/StsExprCreatorVisitor.java, subprojects/xsts-cli/README.md, subprojects/xsts-cli/src/main/java/hu/bme/mit/theta/xsts/cli/XstsCli.java, subprojects/xta-cli/src/main/java/hu/bme/mit/theta/xta/cli/XtaCli.java, subprojects/xta/src/main/java/hu/bme/mit/theta/xta/dsl/XtaExpression.java
This PR adds the `--stacktrace` option to CLI tools, which causes a full stack trace to be printed if an exception occurs. Previously, the stack trace was printed based on the level of logging, but it is better to have it as a separate flag (e.g., frontends do not need logging, but might need the trace). When an exception occurs, its type and message is always printed (previously the message was only printed above a given logging level). Furthermore, the `--stacktrace` option is also printed if not given so that the user knows about it.
Furthermore, a more meaningful error message is given if an identifier cannot be resolved in the Antlr DSLs.
=> Add --stacktrace option to cli tools

build.gradle.kts, subprojects/cfa-analysis/src/main/java/hu/bme/mit/theta/cfa/analysis/DistToErrComparator.java, subprojects/cfa-analysis/src/main/java/hu/bme/mit/theta/cfa/analysis/config/CfaConfigBuilder.java, subprojects/cfa-analysis/src/main/java/hu/bme/mit/theta/cfa/analysis/lts/CfaLbeLts.java, subprojects/cfa-analysis/src/main/java/hu/bme/mit/theta/cfa/analysis/utils/CfaVisualizer.java, subprojects/cfa-analysis/src/test/java/hu/bme/mit/theta/cfa/analysis/CfaTest.java, subprojects/cfa-analysis/src/test/java/hu/bme/mit/theta/cfa/analysis/DistanceToErrorLocComparatorTest.java, subprojects/cfa-analysis/src/test/java/hu/bme/mit/theta/cfa/analysis/EncodingTest.java, subprojects/cfa-analysis/src/test/java/hu/bme/mit/theta/cfa/analysis/impact/CfaPredImpactCheckerTest.java, subprojects/cfa-analysis/src/test/resources/block-encoding.cfa, subprojects/cfa-cli/README.md, subprojects/cfa-cli/src/main/java/hu/bme/mit/theta/cfa/cli/CfaCli.java, subprojects/cfa/README.md, subprojects/cfa/src/main/java/hu/bme/mit/theta/cfa/CFA.java, subprojects/cfa/src/main/java/hu/bme/mit/theta/cfa/dsl/CfaProcessSymbol.java, subprojects/cfa/src/main/java/hu/bme/mit/theta/cfa/dsl/CfaWriter.java
This PR makes the final/error locations of the CFA optional. The motivation behind this is that (1) not all algorithms are interested in them, and (2) sometimes it can be desirable to check multiple queries for the same CFA. The CLI tool was extended in a way that it can accept a `--targetloc` argument. If the argument is given, that location is treated as error, otherwise we fallback to the old solution, namely looking for the error loc in the CFA. This makes the solution backward compatible. See #29 for more information
@as3810t Can you play around a bit with this version?
=> Make error loc of CFA optional, add targetloc argument to CLI tool

build.gradle.kts, subprojects/solver-z3/src/main/java/hu/bme/mit/theta/solver/z3/Z3DeclTransformer.java, subprojects/solver-z3/src/main/java/hu/bme/mit/theta/solver/z3/Z3ExprTransformer.java, subprojects/solver-z3/src/main/java/hu/bme/mit/theta/solver/z3/Z3ItpSolver.java, subprojects/solver-z3/src/main/java/hu/bme/mit/theta/solver/z3/Z3Solver.java, subprojects/solver-z3/src/main/java/hu/bme/mit/theta/solver/z3/Z3SymbolTable.java, subprojects/solver-z3/src/main/java/hu/bme/mit/theta/solver/z3/Z3TermTransformer.java, subprojects/solver-z3/src/main/java/hu/bme/mit/theta/solver/z3/Z3TransformationManager.java, subprojects/solver-z3/src/main/java/hu/bme/mit/theta/solver/z3/Z3TypeTransformer.java, subprojects/solver-z3/src/test/java/hu/bme/mit/theta/solver/z3/Z3SolverTest.java, subprojects/solver/src/main/java/hu/bme/mit/theta/solver/Solver.java, subprojects/solver/src/main/java/hu/bme/mit/theta/solver/Stack.java, subprojects/solver/src/main/java/hu/bme/mit/theta/solver/impl/StackImpl.java, subprojects/solver/src/test/java/hu/bme/mit/theta/solver/StackTest.java
This PR implements the reset function in the Z3 solver. While it is recommended to instead use push/pop, it can be still useful for quick prototyping. Furthermore, some messages were added to exceptions.
Fixes #92
=> Implement reset in Z3 solver

build.gradle.kts, subprojects/common/solver-z3/src/main/java/hu/bme/mit/theta/solver/z3/Z3TermTransformer.java
Fixed a typo in Z3TermTransformer.java which caused errors if the interpolant contained `ArrayWriteExprs`
=> Fixed typo in Z3TermTransformer

build.gradle.kts, subprojects/cfa/cfa/src/main/java/hu/bme/mit/theta/cfa/CFA.java, subprojects/cfa/cfa/src/main/java/hu/bme/mit/theta/cfa/dsl/CfaEdgeDefinition.java, subprojects/cfa/cfa/src/test/java/hu/bme/mit/theta/cfa/CfaTest.java
Previously we could have locations and variables in the same CFA with the same name. This was a bit fragile, because if we serialize the CFA and then parse it back, we might get weird errors (e.g., type of a variable does not match). To prevent these, now the CFA and the CfaBuilder enforces unique variable and location names. Intermediate locations (introduced as a syntactic sugar) now also have names. I bumped the minor version number as this might be a breaking change for frontends. Although if some frontend was relying on this previously that was a bad practice.
=> Check CFA variables and locations for unique names

.github/workflows/gradle-build.yml, doc/Build.md, doc/Development.md, subprojects/cfa/cfa/README.md, subprojects/common/core/src/test/java/hu/bme/mit/theta/core/type/FpTypeTest.java, subprojects/common/solver-z3/src/test/java/hu/bme/mit/theta/solver/z3/Z3SolverFPTest.java
This PR adds a basic Windows build to CI (GitHub actions). Currently it's failing due to a missing library for floats:
```
java.lang.UnsatisfiedLinkError at Z3SolverFPTest.java:45
```
But if we fix that and rebase this PR, I think it should work. But let's wait for that fix first.
=> Add Windows build to CI, disable float tests on Windows.

build.gradle.kts, subprojects/common/analysis/src/main/java/hu/bme/mit/theta/analysis/algorithm/ArgTrace.java
Instead of inserting at first index reverse at the end.
Also did some benchmark on "selected models", there's no consistent, noticeable difference.
=> improved ArgTrace's creation speed

.github/workflows/build-linux.yml
Bash tries to understand `**/jacoco*.xml`, but find is the one who will parse the asterisks.
It leads to a ambigious error message `**/jacoco*.xml not found`
=> Update jacoco workflow

.github/workflows/check-copyright.yml
This PR adds a new GH Action which checks pull requests for the presence of a copyright header in each java and kotlin file. Moving forward, this should be mandatory for all PRs before merge.
=> Added Github Actions task for copyright checking 

.github/workflows/build-win.yml
This PR solves the build error in the windows Github Actions. It installs the 2010 and 2012 VC++ redistributables before attempting to compile Theta.
=> Fix windows build

.github/workflows/deploy-javadoc.yml
This PR enables the javadoc action to check commits on all branches, but only the ones pushed to master will be deployed.
=> Javadoc should only be deployed when pushing to master

.github/workflows/build-win.yml
Can we safely discard the windows-2016 check? It seems to get cancelled on its own for the last few commits.
=> Disabled windows-2016 check, added windows-2022

doc/Build.md, doc/Development.md, subprojects/cfa/cfa-cli/README.md, subprojects/solver/solver-smtlib-cli/README.md, subprojects/sts/sts-cli/README.md, subprojects/xsts/xsts-cli/README.md, subprojects/xta/xta-cli/README.md
Currently, theta uses Java 17, but no documentation has been up-to-date about this. This PR aims to fix this shortcoming.
=> Java 17 doc fix

build.gradle.kts, subprojects/xsts/xsts-analysis/src/main/java/hu/bme/mit/theta/xsts/analysis/XstsState.java, subprojects/xsts/xsts-cli/src/main/java/hu/bme/mit/theta/xsts/cli/XstsCli.java
This patch adds the (already existing) functionality of stopping the analysis if there is no refinement progress to XSTS cli.
(It is merely the addition of a new flag, this feature was already in use with XCFAs.)
The check is ON by default (same as with XCFAs). It can be turned off using the `--no-stuck-check` flag.
If there is no refinement progress and the analysis is constantly rebuilding the same ARGs, it stops the analysis and throws a `NotSolvableException`.
As it is basically a runtime monitoring method, it poses a minimal overhead, but it is barely noticeable, if noticeable at all. None the less, the option to turn it off is there if it is needed, e.g. for debugging.
The monitoring is implemented a bit differently in the case of MULTI_SEQ refinement, but I could not test that with …
=> Adding no refinement progress detection to XSTS cli

build.gradle.kts, subprojects/common/analysis/src/main/java/hu/bme/mit/theta/analysis/prod2/Prod2Prec.java, subprojects/common/analysis/src/main/java/hu/bme/mit/theta/analysis/prod2/Prod2State.java, subprojects/common/analysis/src/main/java/hu/bme/mit/theta/analysis/prod3/Prod3Prec.java, subprojects/common/analysis/src/main/java/hu/bme/mit/theta/analysis/prod3/Prod3State.java, subprojects/common/analysis/src/main/java/hu/bme/mit/theta/analysis/prod4/Prod4Prec.java, subprojects/common/analysis/src/main/java/hu/bme/mit/theta/analysis/prod4/Prod4State.java, subprojects/common/core/src/main/java/hu/bme/mit/theta/core/type/UnaryExpr.java, subprojects/xta/xta-analysis/src/main/java/hu/bme/mit/theta/xta/analysis/expl/itp/ItpExplState.java, subprojects/xta/xta-analysis/src/main/java/hu/bme/mit/theta/xta/analysis/zone/itp/ItpZoneState.java
The last line of hash calculations (`hashCode = result`) was reversed in several States/Expressions resulting in incorrect hash codes.
It seems like I'm the first one to heavily lean on hash codes of states, as no one noticed it before.
It was like this more or less since the beginning of Theta and it was probably propagated by copying and pasting these calculations. I hope I found all of them.
=> Fixed copy-paste error in hash code functions

build.gradle.kts, buildSrc/src/main/kotlin/java-common.gradle.kts, buildSrc/src/main/kotlin/maven-artifact.gradle.kts
This PR adds a new internal Gradle plugin, called `maven-artifact`, which implements the workflow for (eventually) publishing to maven central.
**Right now it publishes to `$HOME/.gradle/.m2/releases`**. This needs to be changed before merge.
My main concern is the integration of this new workflow with the existing build infrastructure.
Use `./gradlew publish -Psigning.secretKeyRingFile=<keyRingFile> -Psigning.password=<pwd> -Psigning.keyId=<keyID>` to try out the publication flow using a PGP key.
=> Added maven publishing to gradle

subprojects/common/core/src/main/java/hu/bme/mit/theta/core/utils/ExprSimplifier.java
This fixes a problem in ExprSimplfier for BvConcatExpr, which removed the operators from the collection when trying to evaluate the expression. 
For an expression `BvLitExpr ++ BvExp`, where the second operand is not BvLitExpr, the simplified version only included the second expression.
=> No more removing ops in exprsimplifier for bvconcat

subprojects/xcfa/xcfa/src/main/java/hu/bme/mit/theta/xcfa/passes/LbePass.kt
Procedures without error locations are not skipped by LBE now
=> LBE pass fix

subprojects/common/core/src/main/java/hu/bme/mit/theta/core/type/inttype/IntLitExpr.java, subprojects/common/core/src/test/java/hu/bme/mit/theta/core/expr/EvaluationTest.java, subprojects/frontends/c-frontend/src/main/java/hu/bme/mit/theta/frontend/transformation/grammar/expression/ExpressionVisitor.java
Fix the discrepancies between the semantics of integer division and modulo in C, Z3 and Theta (see issue #209):
- ebbb6bf: Division in IntLitExpr was calculated using `BigInteger.divide`, which follows C semantics. Converted it to SMT semantics, and added missing tests for integer division to EvaluationTest.
- be73b18: Added conversion from C semantics to SMT semantics to the C-frontend.
=> Harmonize integer div/mod semantics

subprojects/common/analysis/src/main/java/hu/bme/mit/theta/analysis/algorithm/ARG.java, subprojects/common/analysis/src/main/java/hu/bme/mit/theta/analysis/algorithm/ArgEdge.java, subprojects/common/analysis/src/main/java/hu/bme/mit/theta/analysis/algorithm/ArgNode.java, subprojects/common/analysis/src/main/java/hu/bme/mit/theta/analysis/algorithm/ArgStructuralEquality.java, subprojects/common/analysis/src/main/java/hu/bme/mit/theta/analysis/algorithm/ArgTrace.java, subprojects/common/analysis/src/main/java/hu/bme/mit/theta/analysis/runtimemonitor/container/CexHashStorage.kt, subprojects/common/analysis/src/test/java/hu/bme/mit/theta/analysis/algorithm/ArgStructuralEqualityTest.java, subprojects/common/analysis/src/test/java/hu/bme/mit/theta/analysis/stubs/ActionStub.java, subprojects/common/analysis/src/test/java/hu/bme/mit/theta/analysis/stubs/StateStub.java, subprojects/xcfa/xcfa-analysis/src/main/java/hu/bme/mit/theta/xcfa/analysis/XcfaState.kt, subprojects/xcfa/xcfa-cli/src/test/java/hu/bme/mit/theta/xcfa/cli/XcfaCliVerifyTest.kt
This PR fixes the problems with the equals and hashcode implementations of ARG, ArgTrace, ArgNode and ArgEdge.
See issue #219 for reference.
**Do not merge** until benchmarks succeed.
=> ARG equals/hashCode fix

build.gradle.kts, subprojects/solver/solver-smtlib/src/main/java/hu/bme/mit/theta/solver/smtlib/impl/smtinterpol/SMTInterpolSmtLibItpSolver.java
This fixes the issue with #253.
The solution was to change the map to an identity map, thus not referring to other instances of the expression in an interpolant (beforehand, due to equalities among expressions, the last occurrence was always used).
=> Fix smtinterpol interpolation (#253)

build.gradle.kts, subprojects/solver/solver-smtlib/src/main/java/hu/bme/mit/theta/solver/smtlib/impl/cvc5/CVC5SmtLibItpSolver.java, subprojects/solver/solver-smtlib/src/main/java/hu/bme/mit/theta/solver/smtlib/impl/cvc5/CVC5SmtLibSolverInstaller.java, subprojects/solver/solver-smtlib/src/main/java/hu/bme/mit/theta/solver/smtlib/impl/princess/PrincessSmtLibItpSolver.java, subprojects/solver/solver-smtlib/src/main/java/hu/bme/mit/theta/solver/smtlib/impl/princess/PrincessSmtLibSolverInstaller.java, subprojects/solver/solver-smtlib/src/main/java/hu/bme/mit/theta/solver/smtlib/impl/smtinterpol/SMTInterpolSmtLibSolverInstaller.java, subprojects/solver/solver-smtlib/src/main/java/hu/bme/mit/theta/solver/smtlib/impl/z3/Z3SmtLibSolverInstaller.java
This PR fixes some of the JavaSmt-unrelated issues listed in #268 and adds support for newer versions of some solvers:
- `cvc5`: A dummy assertion is added to formula A in case of interpolation.
- `princess`: The HashMap is replaced with IdentityHashMap, similarly to SmtInterpol (#261).
- Support for latest versions of `cvc5`, `Z3` and `princess`.
=> SMTLIB integration fixes

build.gradle.kts, subprojects/common/analysis/build.gradle.kts, subprojects/common/analysis/src/main/java/hu/bme/mit/theta/analysis/algorithm/chc/HornChecker.kt, subprojects/common/analysis/src/test/java/hu/bme/mit/theta/analysis/algorithm/HornTest.kt, subprojects/solver/solver-smtlib/src/main/antlr/SMTLIBv2.g4, subprojects/solver/solver-smtlib/src/main/java/hu/bme/mit/theta/solver/smtlib/impl/generic/GenericSmtLibTermTransformer.java, subprojects/solver/solver-z3/src/main/java/hu/bme/mit/theta/solver/z3/Z3SolverManager.java, subprojects/solver/solver/src/main/java/hu/bme/mit/theta/solver/ProofNode.java, subprojects/xcfa/xcfa-cli/src/main/java/hu/bme/mit/theta/xcfa/cli/checkers/ConfigToChecker.kt, subprojects/xcfa/xcfa-cli/src/main/java/hu/bme/mit/theta/xcfa/cli/checkers/ConfigToHornChecker.kt, subprojects/xcfa/xcfa-cli/src/main/java/hu/bme/mit/theta/xcfa/cli/params/ParamValues.kt, subprojects/xcfa/xcfa-cli/src/main/java/hu/bme/mit/theta/xcfa/cli/params/XcfaConfig.kt, subprojects/xcfa/xcfa-cli/src/test/java/hu/bme/mit/theta/xcfa/cli/XcfaCliVerifyTest.kt
This adds a new SafetyChecker, called HornChecker. Bindings for XCFA were also added.
Right now tested and works with Eldarica, Golem and Z3/SPACER. 
Some aspects of SmtLib parsing were modified/fixed/adapted.
=> Horn checker

build.gradle.kts, subprojects/common/analysis/src/main/java/hu/bme/mit/theta/analysis/algorithm/mdd/expressionnode/MddExpressionRepresentation.java, subprojects/xcfa/xcfa-cli/src/main/java/hu/bme/mit/theta/xcfa/cli/checkers/ConfigToBoundedChecker.kt, subprojects/xcfa/xcfa-cli/src/main/java/hu/bme/mit/theta/xcfa/cli/checkers/ConfigToPortfolio.kt, subprojects/xcfa/xcfa-cli/src/main/java/hu/bme/mit/theta/xcfa/cli/portfolio/bounded.kt, subprojects/xcfa/xcfa-cli/src/test/java/hu/bme/mit/theta/xcfa/cli/XcfaCliVerifyTest.kt
Added a bounded portfolio really similar to the "IMC_THEN_KIND" backend option that was used on SV-COMP with EmergenTheta, but it was then later removed. 
Used solvers: Z3, CVC5:1.0.8, Mathsat:5.6.10, option name: `--portfolio BOUNDED`
=> Added bounded portfolio

build.gradle.kts, subprojects/xsts/xsts/src/main/antlr/XstsDsl.g4
This PR allows `$` in XSTS variable names, closing #265
=> Allow `$` in xsts variable names

build.gradle.kts, subprojects/xsts/xsts-cli/src/main/kotlin/hu/bme/mit/theta/xsts/cli/XstsCliBaseCommand.kt, subprojects/xsts/xsts-cli/src/main/kotlin/hu/bme/mit/theta/xsts/cli/XstsCliChc.kt
This PR adds a different default solver for CHC and fixes cex length printing in XSTS Cli
=> XSTS Cli fixes

.github/workflows/linux-build-test-deploy.yml, build.gradle.kts, subprojects/xcfa/xcfa-cli/src/main/java/hu/bme/mit/theta/xcfa/cli/XcfaCli.kt
We have a new tool this year @ SV-COMP, `Thorn`, which is a portfolio of Theta's HORN-based analyses. This PR adds support for Thorn's binary in the pipeline.
=> Added thorn creation to action

.github/actions/benchexec-report/action.yml, .github/actions/benchexec-test/action.yml, .github/actions/benchexec-test/theta.xml, .github/actions/build-archive/README.md, .github/actions/build-archive/action.yml, .github/actions/build-archive/offset.sh, .github/actions/build-archive/specification-transformation.bin.LICENSE, .github/actions/build-spec-transformation/action.yml, .github/actions/build-spec-transformation/patch.diff, .github/actions/create-release/action.yml, .github/workflows/linux-build-test-deploy.yml, build.gradle.kts, scripts/theta-start.sh
This adds support for pre-transforming between various specifications.
=> Added specification transformation
